name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://blog.taxua.nl/

    - name: Commit and push sitemap
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add sitemap.xml
        git commit -m "Add generated sitemap"
        git push